name: Build Website
on:
  push:
    branches-ignore:
      - gh-pages
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.4.0
      - name: Enable corepack
        run: corepack enable
      - name: Use Yarn 3
        run: yarn set version stable
      - name: Cache dependencies
        uses: actions/cache@v2
        id: cache-dependencies
        with:
          path: |
            .yarn/cache
            .pnp.*
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: Install deps
        if: steps.cache-dependencies.outputs.cache-hit != 'true'
        run: yarn install --immutable
      - name: Lint
        run: yarn lint
      - name: Build for production
        run: yarn build
      - name: Create CNAME file
        run: echo "ericdudley.com" > ./build/CNAME
      - name: Deploy
        if: ${{ github.ref == 'refs/heads/main' }}
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
