name: Build Website
on: [push]
jobs:
  init:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Lint
        run: npm run lint
      - name: Build for production
        run: npm run build
      - name: Deploy
        run: ls -l